export const QKEY_GET_PODIUMS_LIST = "GET_PODIUMS_LIST";

export const QKEY_JOIN_PODIUM = "JOIN_PODIUM";
export const QKEY_GO_LIVE_PODIUM = "GO_LIVE_PODIUM";

export const QKEY_LEAVE_OR_CLOSE_PODIUM = "LEAVE_OR_CLOSE_PODIUM";

export const QKEY_GET_PODIUM_DETAILS = "GET_PODIUM_DETAILS";

export const QKEY_GET_PODIUM_STATS = "GET_PODIUM_STATS";
export const QKEY_GET_PODIUMS_SESSIONS_LIST = "GET_PODIUMS_SESSIONS_LIST";

export const QKEY_GET_WAITING_LIST = "GET_WAITING_LIST";

export const QKEY_SPEAK_REQUEST = "SEND_SPEAK_REQUEST";

export const QKEY_SELF_MUTE = "SELF_MUTE";

export const QKEY_GET_ADMINS_AND_REQUESTS = "GET_ADMINS_AND_REQUESTS";
export const QKEY_GET_PODIUM_BLOCKED_USERS = "GET_PODIUM_BLOCKED_USERS";
export const QKEY_GET_PODIUM_FROZEN_USERS = "GET_PODIUM_FROZEN_USERS";

export const QKEY_BLOCK_OR_UNBLOCK_FROM_PODIUM = "BLOCK_OR_UNBLOCK_FROM_PODIUM";

export const QKEY_FREEZE_OR_UNFREEZE_FROM_PODIUM =
  "FREEZE_OR_UNFREEZE_FROM_PODIUM";

export const QKEY_PAUSE_RESUME_LIVE_CHAT = "PAUSE_OR_RESUME_LIVE_CHAT";

export const QKEY_SEND_PODIUM_INVITATIONS = "SEND_PODIUM_INVITE";

export const QKEY_MAKE_PODIUM_ADMIN = "MAKE_PODIUM_ADMIN";

export const QKEY_CANCEL_PODIUM_ADMIN_INVITE = "CANCEL_PODIUM_ADMIN_INVITE";

export const QKEY_DISMISS_PODIUM_ADMIN = "DISMISS_PODIUM_ADMIN";

export const QKEY_PODIUM_INVITE_TO_SPEAK = "PODIUM_INVITE_TO_SPEAK";

export const QKEY_PODIUM_ACCEPT_INVITE_TO_SPEAK =
  "PODIUM_ACCEPT_INVITE_TO_SPEAK";

export const QKEY_PODIUM_CANCEL_SPEAK_INVITE = "PODIUM_CANCEL_SPEAK_INVITE";

export const QKEY_ACCEPT_OR_DECLINE_PODIUM_INVITE =
  "ACCEPT_OR_PODIUM_DECLINE_INVITE";

export const QKEY_PAUSE_OR_RESUME_PODIUM_GIFT = "PAUSE_PODIUM_GIFT";

export const QKEY_PAUSE_OR_RESUME_PODIUM_PARTICIPANT_GIFT =
  "PAUSE_OR_RESUME_PODIUM_PARTICIPANT_GIFT";

export const QKEY_GET_PODIUM_USER_DETAILS = "PODIUM_USER_DETAILS";
