import { Empowerments, UserFunctionalityBlocks } from "../podiums";

export interface ProfileDataInterface {
  id: number;
  name: string;
  username: string;
  has_password: boolean;
  nicknames: string[];
  verified: boolean;
  empowerments: Empowerments;
  created_on: string;
  email: string;
  phone: string | null;
  country_code_iso: string;
  country_code: string | null;
  country: string;
  dob: string;
  gender: string;
  about: string | null;
  profile_photo: string;
  thumbnail: string;
  device: string | null;
  blocked: boolean;
  account_status: string;
  payment_date: string | null;
  membership: string;
  subscription_status: string;
  active_points: number;
  inactive_points: number;
  fans: number;
  dears: number;
  stars: number;
  likers: number;
  total_performance_points: number;
  is_premium: boolean;
  pp_rate: number;
  is_referrer: boolean;
  location_skipped: boolean;
  referral_link: string;
  longitude: number;
  latitude: number;
  profile_complete_percentage: number;
  subscription_expiration_date: string;
  broadcast_delete_timeout: number;
  huddle_message_delete_timeout: number;
  private_message_delete_timeout: number;
  video_duration_limit: number;
  total_broadcasts: number;
  total_likes: number;
  huddle_participants_limit_for_free: number;
  flax_rate: number;
  flax_rate_percentage: number;
  flax_increment: boolean;
  citizenship: string;
  flash_duration: number;
  allow_change_location: boolean;
  allow_hide_country_flag: boolean;
  total_gift_points: number;
  total_received_points: number;
  total_received_points_thismonth: number;
  user_gift_sum: number;
  remaining_days_for_resident: number;
  show_country_flag: boolean;
  is_country_flag_enabled: boolean;
  contributor_level: string;
  player_level: string;
  subscription_expiry_date: string;
  total_flash_published: number;
  total_public_podiums: number;
  issue_date: string;
  is_birthday_today: boolean;
  flash_block: boolean;
  user_functionality_blocks: UserFunctionalityBlocks;
  user_uuid: string;
  user_level_animation_url: string;
  citizenship_priority: number;
  is_flix_subscription_renewed: boolean | null;
  location_changed: boolean | null;
  total_postat_posts: number;
  diamond_likes: number;
}
